# This script (monitor.py) was generated by Claude Opus 5.5 with Medium thinking by using the below prompt. It samples CPU and memory usage on the VM in a background thread,
# sends a Discord alert when a threshold is exceeded, and exposes a warning banner
# for the Gradio app to display.
# Prompt inputted into Claude Opus 5.5: Can you add a monitoring mechanism that tracks resource usage on the virtual machine including CPU and memory usage? I want to send a notification using my discord webhook when one of these resources exceeds a certain threshold. I also need to display a warning message on the web app saying when this threshold has been reached.

import json
import os
import socket
import threading
import time
import urllib.request

import psutil

CPU_THRESHOLD = float(os.environ.get("CPU_THRESHOLD", 85))  # percent
MEM_THRESHOLD = float(os.environ.get("MEM_THRESHOLD", 85))  # percent
CHECK_INTERVAL = 5     # seconds averaged per sample
ALERT_COOLDOWN = 300   # seconds before alerting again for the same resource
WEBHOOK_URL = os.environ.get("DISCORD_WEBHOOK_URL")
HOSTNAME = socket.gethostname()

# Latest readings, written by the monitor thread and read by the web app.
# "since" maps a resource name to the time it first went over its threshold.
status = {"cpu": 0.0, "mem": 0.0, "since": {}}
_last_alert = {}


def send_discord_alert(message):
    if not WEBHOOK_URL:
        print(f"[MONITOR] DISCORD_WEBHOOK_URL not set, skipping alert: {message}")
        return
    request = urllib.request.Request(
        WEBHOOK_URL,
        data=json.dumps({"content": message}).encode(),
        # Discord rejects Python's default User-Agent, so set our own
        headers={"Content-Type": "application/json", "User-Agent": "CS553-resource-monitor"},
    )
    try:
        urllib.request.urlopen(request, timeout=10)
    except Exception as e:
        print(f"[MONITOR] Failed to send Discord alert: {e}")


def _check(name, value, threshold):
    now = time.time()
    if value < threshold:
        status["since"].pop(name, None)
        return
    status["since"].setdefault(name, now)
    if now - _last_alert.get(name, 0) >= ALERT_COOLDOWN:
        _last_alert[name] = now
        send_discord_alert(
            f"WARNING **{name} usage high on {HOSTNAME}**: {value:.1f}% (threshold {threshold:.0f}%)"
        )


def _monitor_loop():
    while True:
        cpu = psutil.cpu_percent(interval=CHECK_INTERVAL)  # blocks for CHECK_INTERVAL seconds
        mem = psutil.virtual_memory().percent
        status["cpu"], status["mem"] = cpu, mem
        _check("CPU", cpu, CPU_THRESHOLD)
        _check("Memory", mem, MEM_THRESHOLD)


def start_monitor():
    threading.Thread(target=_monitor_loop, daemon=True).start()


def get_warning_html():
    """Return a red warning banner for each resource over its threshold, or "" if none."""
    readings = {"CPU": (status["cpu"], CPU_THRESHOLD), "Memory": (status["mem"], MEM_THRESHOLD)}
    lines = []
    for name, since in status["since"].items():
        value, threshold = readings[name]
        started = time.strftime("%H:%M:%S", time.localtime(since))
        lines.append(
            f"WARNING <b>{name} usage is {value:.1f}%</b>, above the {threshold:.0f}% threshold "
            f"(since {started}). Responses may be slow."
        )
    if not lines:
        return ""
    return '<div id="resource-warning">' + "<br>".join(lines) + "</div>"
