#!/bin/bash
#Script generated by ChatGPT, asked it to setup virtual environment based on our app.py file

set -e

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="$PROJECT_DIR/.venv"
REQUIREMENTS_FILE="$PROJECT_DIR/requirements.txt"

echo "Project directory: $PROJECT_DIR"

cd "$PROJECT_DIR"

echo "Checking Python..."
if ! command -v python3 >/dev/null 2>&1; then
    echo "ERROR: Python 3 is not installed."
    echo "Install it with:"
    echo "  sudo apt update"
    echo "  sudo apt install -y python3 python3-venv python3-pip"
    exit 1
fi

echo "Checking requirements.txt..."
if [ ! -f "$REQUIREMENTS_FILE" ]; then
    echo "ERROR: requirements.txt not found at:"
    echo "  $REQUIREMENTS_FILE"
    exit 1
fi

# Updated the following block of code with Claude Opus 5.5 on Medium thinking when asked why pip was not installing on the remote machine (issue was caused due to lack of)
echo "Creating virtual environment..."
if [ ! -x "$VENV_DIR/bin/pip" ]; then
    rm -rf "$VENV_DIR"
    python3 -m venv --without-pip "$VENV_DIR"
    curl -sS https://bootstrap.pypa.io/get-pip.py | "$VENV_DIR/bin/python"
else
    echo "Virtual environment already exists."
fi


echo "Activating virtual environment..."
source "$VENV_DIR/bin/activate"

echo "Upgrading pip..."
python -m pip install --upgrade pip

echo "Installing dependencies from requirements.txt..."
python -m pip install -r "$REQUIREMENTS_FILE"

# The below code segment was suggested by Claude Opus 5.5 on Medium thinking when asked how to securely send my HuggingFace token to the class vm
echo "Setup complete."

echo "Stopping any previously running app..."
pkill -f "$VENV_DIR/bin/python app.py" || true

if [ -f "$HOME/.hf_token" ]; then
    export HF_TOKEN="$(cat "$HOME/.hf_token")"
else
    echo "WARNING: ~/.hf_token not found, remote model will not work"
fi

# Suggested by Claude Opus 5.5 on Medium thinking in conjunction with monitor.py
if [ -f "$HOME/.discord_webhook" ]; then
    export DISCORD_WEBHOOK_URL="$(cat "$HOME/.discord_webhook")"
else
    echo "WARNING: ~/.discord_webhook not found, resource alerts will not be sent to Discord"
fi

echo "Starting app..."
nohup "$VENV_DIR/bin/python" app.py > "$PROJECT_DIR/log.txt" 2>&1 < /dev/null &
echo "App started with PID $! (log: $PROJECT_DIR/log.txt)"
