#!/bin/bash
#Script generated by ChatGPT, asked it to setup virtual environment based on our app.py file

set -e

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="$PROJECT_DIR/.venv"
REQUIREMENTS_FILE="$PROJECT_DIR/requirements.txt"

echo "Project directory: $PROJECT_DIR"

cd "$PROJECT_DIR"

echo "Checking Python..."
if ! command -v python3 >/dev/null 2>&1; then
    echo "ERROR: Python 3 is not installed."
    echo "Install it with:"
    echo "  sudo apt update"
    echo "  sudo apt install -y python3 python3-venv python3-pip"
    exit 1
fi

echo "Checking requirements.txt..."
if [ ! -f "$REQUIREMENTS_FILE" ]; then
    echo "ERROR: requirements.txt not found at:"
    echo "  $REQUIREMENTS_FILE"
    exit 1
fi

echo "Creating virtual environment..."
if [ ! -d "$VENV_DIR" ]; then
    apt install python3-venv
    python3 -m venv "$VENV_DIR"
else
    echo "Virtual environment already exists."
fi

echo "Activating virtual environment..."
source "$VENV_DIR/bin/activate"

echo "Upgrading pip..."
python -m pip install --upgrade pip

echo "Installing dependencies from requirements.txt..."
python -m pip install -r "$REQUIREMENTS_FILE"

echo
echo "Setup complete."
echo
echo "Virtual environment:"
echo "  $VENV_DIR"
echo
echo "To activate it manually:"
echo "  cd $PROJECT_DIR"
echo "  source .venv/bin/activate"
```